### ISSUE TITLE
IN GEM5 + NVMAIN..YOU DIDN'T ADDED THE M5 PATH

### ISSUE THREAD

**Issue by gautamuk** [samueltphd/NVmain#2]
I think it is necessary to add the m5 path for binaries we have downloaded in gem5..if you did so..Explain how?

**Comment by samueltphd** [comment]
You can get the m5 path binaries from https://www.gem5.org/documentation/general_docs/fullsystem/guest_binaries by calling wget on the binary that you would like to include. It's part of the normal gem5 installation documentation.
